version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version you want to use
    commands:
      - echo Installing dependencies...
      - pip install pytest
  build:
    commands:
      - echo Running tests...
      - pytest test_lambda_function.py
